### ISSUE TITLE
Document "local sandbox" instructions for PRs somewhere

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#122]
### Background

There is desire, particularly around frontend developers, to spin up a cloud-hosted sandbox, running Open edX with a specific version of each service & frontend whenever a PR is made. That would allow reviewers to easily test out changes.

Until we have that, we could help PR reviewers leverage Tutor to create a "local sandbox" for any given PR. The idea is that we'd have some template of Tutor commands that a PR author could fill in. The author would include the commands in their PR description. Reviewers could run the commands on their computer in order to get a local sandbox.

### Tasks

- [ ] Come up with a set of Tutor commands that, when run:
   * configures Tutor to a run certain versions of edx-platform, the frontend in question, and any other necessary apps;
   * builds images; and
   * starts the platform.
- [ ] Document these commands somewhere so that PR authors can include them in the PR descriptions for reviewers to use.
- [ ] Add these commands to the frontend-template-application PR template.

**Comment by kdmccormick** [comment]
@brian-smith-tcril just letting you know, I didn't get to this as quickly as I thought I would, but I haven't forgotten about it.

**Comment by kdmccormick** [comment]
This is a still a good idea, but I'm not going to be able to work on it any time soon.
