### ISSUE TITLE
Tutor Adoption 4: Devstack Parity: Improve Dev Workflows

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#146]
### Background

https://github.com/openedx/wg-developer-experience/issues/144 describes three options for improving `tutor dev` workflows around locally-changed code and requirements. This is one option.

```[tasklist]
### Tasks
- [x] https://github.com/openedx/wg-developer-experience/issues/152
- [x] https://github.com/overhangio/tutor/pull/813
- [ ] https://github.com/openedx/edx-platform/issues/31798
- [ ] https://github.com/openedx/wg-developer-experience/issues/150
- [ ] https://github.com/openedx/wg-devops/issues/22
- [ ] https://github.com/openedx/wg-developer-experience/issues/162
- [ ] https://github.com/openedx/wg-devops/issues/21
- [ ] https://github.com/kdmccormick/tutor/pull/32
- [ ] https://github.com/kdmccormick/tutor/pull/33
- [ ] https://github.com/openedx/wg-developer-experience/issues/177
- [ ] https://github.com/openedx/wg-developer-experience/issues/159
```

### Notes

These tasks are based on [this comment from the quickdev TEP]():

> I too want to make sure we are solving the right problems rather than applying workarounds to things that are broken on a deeper level. Let me break down the problems I see with tutor dev as a it stands.
> #### node_modules
> I’m no npm expert, but from my research it seems that npm really wants node_modules to be stored in the root of the repository itself. The ways around this I can think of are:
> 1. Install all packages in “global” mode (npm -g) so that they are installed somewhere in the container outside of the repository. In a prototype I was able to [hackily achieve this](https://github.com/kdmccormick/tutor/pull/17/files#diff-54494c0be558fb597a3d8578be512225985a5d7459d8dac90d62d4c366111c80) by shadowing the npm binary with a script that forwarded all arguments to npm -g. This would also require [further unraveling of the paver-based assets pipeline](https://github.com/kdmccormick/tutor/pull/17/files#diff-2bfcf77b38c5be0f588b5d5af1d4311581dcc6bce5d4abea415234adf73987a2), which is a good thing anyway, and is something I think we could get 2U’s help on.
> 2. In the dev Docker image, move /openedx/edx-platform/node_modules to /openedx/node_modules and replace the former with a link to the latter. Then, do the same thing for mounted repositories using an ENTRYPOINT script. I [had this idea working](https://github.com/kdmccormick/tutor-contrib-kdmccormick/commit/44ce4765644fc59515b63b78c972edd4f5330de2#diff-6df6f7965f7d8834833c038bb9479ba901d7a4f8b16a139106e520693c1edad1R56-R65) in an earlier version of quickdev, but dropped it because it seemed too hacky.
> 3. For micro-frontends, stop trying to use Docker containers in development mode. For backend services, just accept that we will have this problem until all legacy frontends are removed and our backends are purely JSON API servers.
> #### python virtualenv
> Thankfully, since the venv is stored at /openedx/venv, which is outside of edx-platform, running `pip install -r requirements/dev.txt` isn’t required after mounting a repository. However, people often want to modify Python requirements and/or install local versions of packages without too much of a hassle.
> Outside of turning the venv into a named volume, I think the best improvement we could make would be to speed up the dev image build as much as possible. That way, it is much faster for developers to update edx-platform’s requirements lists and re-build the image. A few ideas I have:
> * [Convert GitHub dependencies to PyPI requirements wherever possible](https://github.com/openedx/wg-developer-experience/issues/153). This is already in progress, and I could push to expedite if we decide against quickdev.
> * [Hunt down and remove extraneous edx-platform requirements](https://github.com/openedx/edx-platform/issues/31505). Easier said than done, but it’s something the project ought to do at some point anyway.
> * [Convince Docker to use the downloaded & cached version of the openedx image when re-building openedx-dev](https://github.com/openedx/wg-devops/issues/19). That is: for me, at least, it seems like Docker wants to re-build the image from scratch when I run tutor dev dc build lms, even if I just ran tutor images pull openedx… there’s got do be something we can do to re-use those downloaded stages from the production image.
> #### static assets
> I’m not very knowledgable here but I’m sure the situation could be improved upstream. There’s discussion about the asset pipeline [on this github issue](https://github.com/openedx/frontend-wg/issues/126). Even without overhauling the whole edx-platform asset pipeline, I have to hope that’s there’s something we could do to move the generated assets out of edx-platform…
> #### jobs
> This one’s already in progress but it’s worth mentioning anyway: having the [pluggable jobs framework](https://github.com/overhangio/tutor/pull/738) merged should help us condense any remaining “mounting repository preparation” commands down into single command, e.g. tutor dev do prepare-mounted-platform --mount=edx-platform.
> #### egg-info
> This one’s fairly minor, but as far as I can tell, edx-platform will always need Open_edX.egg-info file to be present in the repository. If we don’t use a named volume, this means that pip install -e . is non-optional. I think the jobs framework, mentioned above, could handle this nicely.

**Comment by regisb** [comment]
I think it's great that you are attempting to resolve the underlying issues by attacking edx-platform directly. It's certainly the most difficult path forward, but also the one with the most potential. Let me know how if I can help.

**Comment by bradenmacdonald** [comment]
> python virtualenv

For me one of the recurring problems is that the edx-platform dependencies change all the time... 

```
$ tutor dev start
... gives some error ...
$ tutor quickdev pip-restore
$ tutor dev start
... now it works
```
But later I need a custom edx-platform:
```
tutor dev start -m ~/edx-platform
... gives some error depending on what's changed, like: ImportError: cannot import name 'VerticalBlockRenderCompleted' from 'openedx_filters.learning.filters'
$ tutor dev run -m ~/edx-platform lms pip install -r requirements/edx/development.txt
$ tutor dev run -m ~/edx-platform lms ./manage.py lms migrate 
... now it works
```

What I think we need is some way that we can automatically detect when there's a difference between the requirements specified in the current `requirements/*.txt` file(s) and the actual venv in use, and then automatically update the venv to match before launching the dev environment. If this were possible, it would solve the primary annoyance I have using Tutor as a devstack, which is that it's very unclear what pieces are working together and which command will "reset" things so that the right tutor version is used with the right edx-platform version is used with the right venv is updated to the right requirements versions so that everything works.

Or another way of phrasing that is, can things like https://github.com/openedx/wg-developer-experience/issues/153 and https://github.com/openedx/edx-platform/issues/31505 take us far enough that we run `pip install` automatically every time we start `tutor dev`, so that the "right" requirements are always installed in the venv ?

**Comment by bradenmacdonald** [comment]
@kdmccormick Thanks! I'm not knowledgeable enough to predict how well your two ideas would work, but they're great ideas and I'd be very interested in seeing what happens if we try them out.

**Comment by kdmccormick** [comment]
> Would it make our lives easier if we moved /openedx/venv to /openedx/edx-platform/.venv? That way, an edx-platform's venv would be automatically bind-mounted every time we bind-mount edx-platform. I realize it would be a sort of step backward, as we are trying to move stuff away from edx-platform... Still, it's probably worth considering.

Agreed, it is worth considering. It makes me realize that bind-mounted tutor dev is currently in an awkward middle ground. One very important thing lives in the image:
* the Python venv

whereas the rest of it lives in the bind-mount:
* the Python requirements list
* package-lock.json
* node_modules
* compiled assets

Perhaps we should pick a side. I am interesting in prototyping the first one. If you prototype the second one, we could compare results.

### Install/compile everything into the image

This is the direction I've been heading. Firstly, I would do either (1) or (2) from my previous comment. 

Then, I would implement https://github.com/openedx/wg-developer-experience/issues/150 and https://github.com/openedx/wg-developer-experience/issues/151, or some variation of those issues.

### Install/compile everything into the bind-mount

We would move /openedx/venv to /openedx/edx-platform/.venv. We could pip-install Python requirements again when initializating a bind-mounted platform. This would probably work well enough for Linux.

Unfortunately, writing to bind-mounts on macOS is catastrophically slow, so asking those devs to run `pip install` (or, for that matter, `npm install`) into the bind-mount is just cruel. However, we could copy the node_modules and .venv directories down from the image to the host.

The current implementation of the `copyfrom` command, unfortunately, will not work well on macOS, because it's implemented using a bind-mount. I think it could be reimplemented using `docker cp`, though.

**Comment by bradenmacdonald** [comment]
> Unfortunately, writing to bind-mounts on macOS is catastrophically slow, so asking those devs to run pip install (or, for that matter, npm install) into the bind-mount is just cruel. However, we could copy the node_modules and .venv directories down from the image to the host.

FWIW I measured this just now; once the pip cache is populated, `pip install -r requirements/edx/base.txt` takes 1m5s using a Docker volume but 4m15s using a bind mount (virtiofs). I imagine the platform would also run slower if python has to read all of the .pyc files out of a bind mount instead of just some.

**Comment by kdmccormick** [comment]
The major macOS constraint I've become aware of is *don't write anything significant to bind-mounts*. The two solutions that leads me to are:
* Use named volumes instead of bindmounts (ie, quickdev). This works well, but it introduces spooky background state into everyone's development environment.
* Build as much as possible into the image (options 1 and 2 above). I haven't tried this yet, but I'm eager to.

FWIW, I do have a Mac to test on now.

**Comment by bradenmacdonald** [comment]
Yeah, using a virtual environment in the container is totally fine, as long as it's not bind-mounted. The problem is just that python doesn't have a simple/fast way to keep that venv in sync with the requirements files. Ideally there would be some readonly `venv` in the base image, and a writeable `venv` layer over top of it, and something that automatically rebuilds the writable venv delta whenever it no longer matches the requirements files. This could be as simple as a hacky script to make a hash of the requirements files and write that to the venv folder after each `pip install`, plus repeating that automatically when the hash doesn't match.

**Comment by regisb** [comment]
I am tempted to say that optimizing bind-mounts for macOS should not be our job, but then it seems that there are no practical solutions proposed upstream: https://github.com/docker/for-mac/issues/3677

So we don't really have a choice, right? I am still not in favour of named volumes, so the only option left is to build as much as possible into the image, such that the bind-mounted volumes remain as small as possible.

The good news is that I think we can achieve this without burdening the developers too much. I have a working proof of concept that works as follows:

- At build-time, bind-mount the source repo in the image using a build-context. See example 3 from [this article](https://www.docker.com/blog/dockerfiles-now-support-multiple-build-contexts/) and [this section](https://docs.docker.com/engine/reference/commandline/buildx_build/#build-context) of the Docker docs. Thanks to the `--build-context` option we should be able to implement a `tutor images build --bind-mount=/path/to/edx-platform` option.
- Aggressively cache `pip install` and `npm clean-install` commands using [`RUN --mount=type=cache,...`](https://docs.docker.com/engine/reference/builder/#run---mounttypecache) commands. In Olive my proof of concept is still slowed-down by edx-platform editable requirements but this will get better in Palm thanks to [Kyle's efforts](https://github.com/openedx/edx-platform/pull/30719).
- Persistent bind-mounts which allow developers to run `tutor dev bind-mount /path/to/edx-platform` once instead of adding the `-m /path/to/edx-platform` to every command. I haven't implemented this command yet, but it should not be too hard.
- Move `/openedx/edx-platform/node_modules` to `/openedx/node_modules` and symlink to it (Kyle this is your option 2 above). I have just attempted to do this and it seems to be working as expected.

So I think we can attempt to resolve this issue using this approach.

>  Ideally there would be some readonly venv in the base image, and a writeable venv layer over top of it

This is a really interesting idea. I understand we could achieve that goal with a quick-and-dirty script, but I wonder if there is any "official" way to run a combination of multiple virtualenv?

**Comment by bradenmacdonald** [comment]
> This is a really interesting idea. I understand we could achieve that goal with a quick-and-dirty script, but I wonder if there is any "official" way to run a combination of multiple virtualenv?

Doesn't docker do this for us already though, if the base venv layer is established during the build, then it becomes readonly and any changes made it the container will be done in a copy-on-write overlay of the venv, as long as it's not bind mounted.

**Comment by kdmccormick** [comment]
We've made a lot of progress here, so I'm closing this, with two remaining follow-up issues:
* https://github.com/openedx/wg-devops/issues/21
* https://github.com/openedx/wg-devops/issues/22
