### ISSUE TITLE
Move static assets outside of edx-platform in Tutor's openedx image

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#151]
### Background

This is a sub-task of https://github.com/openedx/wg-developer-experience/issues/146.

**The problem:** In the openedx image, static assets are collected & compiled into [several sub-directories of /openedx/edx-platform/](https://github.com/kdmccormick/tutor-contrib-kdmccormick/blob/88ffa2fa799d91d192642ba3ce90564c3b4e2d40/tutorkdmccormick/quickdev.py#L121-L138). So, when you mount your own edx-platform, you override all of those static asset folders. Now, you must re-build assets yourself (`tutor dev run --mount=edx-platform openedx-assets build --env=dev`), which takes a while time and is completely redundant with the assets that you had to download when you downloaded the openedx image. If you forget to do this, then your edx-platform frontend will be broken.

**What we want:** To generate static assets outside of the /openedx/edx-platform directory so that mounting edx-platform does not overwrite them. 

### Tasks

- [ ] Figure out how to change where static assets go.
- [ ] Figure out how this interacts with a developer's desire to rebuild assets that they have changed. In other words, as a developer, would `tutor dev run --mount=edx-platform openedx-assets build --env=dev` work if I *wanted* to re-run it?
- [ ] Implement the solution or write up issues for it.
- [ ] Triumphantly strike the `openedx-assets build --env=dev` step from [Tutor's dev env setup instructions](https://docs.tutor.overhang.io/dev.html#setting-up-a-development-environment-for-edx-platform).

**Comment by kdmccormick** [comment]
Blocked by https://github.com/openedx/edx-platform/issues/31798
