### ISSUE TITLE
Install all edx-platform dependencies from PyPI, not GitHub

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#153]
## Background

Several edx-platform packages are installed directly from GitHub instead of PyPI. See: [edx-platform's github.in](https://github.com/openedx/edx-platform/blob/master/requirements/edx/github.in). This is non-ideal because:
* GitHub-hosted requirements take significantly longer (> 4x) to install than PyPI-hosted requirements (I care about this for Tutor build speed :)
* GitHub-hosted requirement pins cannot be upgraded using our standard `make upgrade` workflow.

## Acceptance Criteria

In edx-platform, remove all packages from github.in.

Investigate use of GitHub-hosted deps in other IDAs. Remove them, or create follow-up tickets.

Add guidance that steers developers away from using GitHub-hosted deps and/or makes it easier for them to publish their packages to PyPI. Consider using a repo health check or CODEOWNERS to help us hold ourselves to this.

```[tasklist]
### Tasks
   - [x] https://github.com/openedx/open-edx-proposals/pull/390
   - [x] https://github.com/openedx/edx-platform/pull/30719
   - [x] https://github.com/openedx/edx-platform/pull/31104
   - [x] https://github.com/openedx/open-edx-proposals/pull/450
   - [x] https://github.com/openedx/edx-platform/pull/31824
   - [x] https://github.com/openedx/codejail/pull/140
   - [x] https://github.com/openedx/codejail/pull/151
   - [x] https://github.com/openedx/edx-platform/pull/31683
   - [x] https://github.com/openedx/RateXBlock/issues/45
   - [x] https://github.com/openedx/xblock-drag-and-drop-v2/issues/299
   - [x] https://github.com/openedx/blockstore/pull/202
   - [x] https://github.com/openedx/edx-platform/pull/30601
   - [x] https://github.com/openedx/edx-platform/pull/31236
   - [x] https://github.com/openedx/blockstore/issues/212
   - [x] https://github.com/openedx/edx-platform/pull/31271
   - [ ] https://github.com/openedx/MongoDBProxy/issues/18
   - [x] https://github.com/openedx/olxcleaner/pull/16
   - [x] https://github.com/openedx/olxcleaner/pull/17
   - [x] https://github.com/openedx/edx-platform/pull/31819
   - [x] https://github.com/openedx/edx-platform/pull/31279
   - [x] https://github.com/open-craft/xblock-poll/issues/98
   - [x] https://github.com/openedx/edx-platform/pull/31718
   - [x] https://github.com/openedx/edx-platform/pull/31201
```

**Comment by UsamaSadiq** [comment]
Created [PR](https://github.com/openedx/edx-platform/pull/31819) to move `olxcleaner` from GitHub to PyPI. It'll be merged after completely testing the change using sandbox.

**Comment by kdmccormick** [comment]
As of today, [github.in](https://github.com/openedx/edx-platform/blob/2d9c528827ff917cccc1cbb696913f7a9746d230/requirements/edx/github.in) is empty!
