### ISSUE TITLE
Discuss vision doc and reach some form of consensus

### ISSUE THREAD

**Issue by jmbowman** [openedx/wg-developer-experience#158]
### Background

I wrote a draft [Development Environment Vision](https://openedx.atlassian.net/wiki/spaces/AC/pages/3615850497/Development+Environment+Vision) document to form a clearer idea of what we ultimately want from an Open edX developer environment, and how we can get there.  Feedback was requested in Discourse at https://discuss.openedx.org/t/feedback-requested-development-environment-vision/9069/2 (as well as in the Open edX and 2U Slack workspaces and an email to 2U Open edX developers).  Discussion is ongoing in document comments, but I also think it's worth keeping track of the overall status of the discussion here.

### Tasks

- [ ] Make sure the discussion doesn't lose momentum before reaching some kind of consensus
- [ ] Revise the document as appropriate in response to feedback
- [ ] Once the document reaches a relatively stable state, capture action items from the document and discussion and assign them to appropriate people
