### ISSUE TITLE
Run cypress-e2e-tests in Tutor?

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#164]
### Background

The old end-to-end testing suite for edx-platform was the bok-choy-based https://github.com/edx/edx-e2e-tests. It is deprecated and no longer runs for edx.org.

There is a new suite: https://github.com/openedx/cypress-e2e-tests. I hear that it is running for edx.org?

If this test suite is for real, then it'd be good to find someone to make a plugin for it.

### Tasks

- [ ] Find out who owns/maintains https://github.com/openedx/cypress-e2e-tests
- [ ] Figure out where these tests are run right now -- edx.org? devstack?
- [ ] Figure out whether they are ready to be used by other Open edX operators.
- [ ] If yes the above, then:
  - [ ] Ask the owners/maintainers to include this the repo in the next Open edX release.
  - [ ] Do some light discovery on what it would take to get them running it Tutor. Presumably, a plugin is the right way to go (confirm this). Write up a follow-up issue.
- [ ] If no:
  - [ ] Document here what it would take for cypress-e2e-tests to be ready for the Open edX community to use.
