### ISSUE TITLE
Do we still need `-job` containers?

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#165]
### Background

The cms and lms services both have "job" variants: cms-job and lms-job. Plugins are encouraged to make job variants of their services, e.g. discovery and discovery-job. The special docker-compose YAML files for jobs, and special patches for those YAML files.

They are used when running "`do`" jobs (including migrations & other db provisioning). I don't believe they're used for anything else.

### Tasks

- [ ] Enumerate differences between lms-job/cms-job and lms/cms containers. Known differences:
  * they don't have tty and stdin_open enabled
  * they don't mount themes or custom requirements
- [ ] Are job containers still necessary, rather then using the normal containers for everything?
- [ ] If so:
  - [ ] Add a comment explaining why
- [ ] If not:
  - [ ] Make an issue to get rid of them.

**Comment by kdmccormick** [comment]
Tangentially related: https://github.com/overhangio/tutor/pull/814

**Comment by kdmccormick** [comment]
@regisb , I recall you posting a great explanation somewhere of why we do need to keep the `-job` containers, but for the life of me I can't find it. If you remember what I'm talking about, could you link it here?

**Comment by regisb** [comment]
Yes, I wrote down my thoughts here: https://github.com/overhangio/tutor/issues/642#issuecomment-1483970113

**Comment by kdmccormick** [comment]
Great, thanks!

**Comment by kdmccormick** [comment]
Proposal to explain this in docker-compose.jobs.yml: https://github.com/overhangio/tutor/pull/832
