### ISSUE TITLE
DevX: Catch-All Bucket

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#167]
### Background

A place to collect work related to the Developer Experience Working Group that doesn't neatly fit into any of the existing epics (yet).

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/devstack/issues/943
- [ ] https://github.com/openedx/wg-devops/issues/38
- [ ] https://github.com/openedx/wg-developer-experience/issues/136
- [ ] https://github.com/openedx/wg-developer-experience/issues/154
- [ ] https://github.com/openedx/wg-developer-experience/issues/134
- [ ] https://github.com/openedx/wg-developer-experience/issues/122
- [ ] https://github.com/edx/edx-arch-experiments/issues/83
- [ ] https://github.com/openedx/wg-developer-experience/issues/139
- [ ] https://github.com/edx/edx-arch-experiments/issues/152
- [ ] https://github.com/openedx/wg-developer-experience/issues/158
- [ ] https://github.com/openedx/wg-developer-experience/issues/137
- [ ] https://github.com/openedx/tcril-engineering/issues/67
- [ ] https://github.com/openedx/tcril-engineering/issues/68
- [ ] https://github.com/openedx/wg-developer-experience/issues/62
- [ ] https://github.com/openedx/wg-developer-experience/issues/47
- [ ] https://github.com/openedx/wg-developer-experience/issues/24
- [ ] https://github.com/openedx/wg-developer-experience/issues/23
- [ ] https://github.com/openedx/wg-developer-experience/issues/149
- [ ] https://github.com/openedx/wg-developer-experience/issues/138
- [x] https://github.com/openedx/wg-build-test-release/issues/138
```

**Comment by kdmccormick** [comment]
I've moved the remaining relevant issues to https://github.com/openedx/wg-devops
