### ISSUE TITLE
Collecting development metrics

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#169]
### Background

2U's Arch-BOM team is leading a careful analysis of the options for measuring the success of our developer experience initiatives. This includes exploring which metrics are the most valuable as well as determining how they will be measured, and which, if any, 3rd party tools will help.

### Tasks

```[tasklist]
- [ ] https://github.com/edx/edx-arch-experiments/issues/84
- [ ] https://github.com/edx/edx-arch-experiments/issues/169
- [ ] https://github.com/edx/edx-arch-experiments/issues/168
- [ ] https://github.com/edx/edx-arch-experiments/issues/167
```

**Comment by kdmccormick** [comment]
No longer planned due to limited DevX resources at 2U.
