### ISSUE TITLE
Options for remote development

### ISSUE THREAD

**Issue by rgraber** [openedx/wg-developer-experience#171]
### Background

The Arch-BOM team at 2u is exploring options for remote development environments as part of their larger DevEx work. This issue is to track the work being done in that area for greater visibility.

```[tasklist]
### Tasks
- [ ] https://github.com/edx/edx-arch-experiments/issues/82
- [ ] https://github.com/edx/edx-arch-experiments/issues/93
- [ ] https://github.com/edx/edx-arch-experiments/issues/203
- [ ] https://github.com/openedx/wg-developer-experience/issues/173
```

**Comment by kdmccormick** [comment]
No longer planned due to limited DevX resources at 2U.
