### ISSUE TITLE
Automatically `tutor config save` after enabling/disabling a plugin

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#176]
### Background

Every time you run `tutor plugins [enable/disable] PLUGIN`, it warns you that you should now render your config with `tutor config save`. Why not just run `tutor config save` automatically? 

### Tasks

- [ ] Save config as part of plugin enable/disable.
- [ ] Add a unit test.
- [ ] Manually test, including the case where the plugin has a syntax or a name error in it.
- [ ] Add it to the changelog.

### Notes

* Follow-up:
  * are there any other commands that would make sense to automatically do `tutor config save` after?
  * going a step further, could we make it so the *only* time you need to run `tutor config save` is if you hand-edit config.yml? At that point, perhaps could we rename it to `tutor config apply`?
* Pros:
  * Less typing.
  * Less things users can forget to do.
* Cons:
  *  A bit more magical, less explicit.
      * Counterargument: Some other commands already `tutor config save` for you. For example, `tutor mounts [add/remove]`.
  * Is there ever a time when we'd want to enable or disable a plugin but *not* apply the change the `env/` folder? I can't think of one, except maybe when the plugin has an error. Related:
    * https://github.com/openedx/wg-developer-experience/issues/83

**Comment by CodeWithEmad** [comment]
Hello there! I'd like to give it a try.
Any additional information or suggestions would be highly appreciated.
Thank you!

**Comment by regisb** [comment]
Let's just do the base feature for now (run `tutor config save` after `tutor plugins enable/disable`) and we'll think about the follow up later. I think you have enough to get started, and we can always discuss further in the PR.

**Comment by CodeWithEmad** [comment]
Closed in favor of https://github.com/overhangio/tutor/pull/957

**Comment by CodeWithEmad** [comment]
We can close this because of https://github.com/overhangio/tutor/pull/957
